# Generated by Django 3.2.13 on 2022-07-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='gold',
            field=models.DecimalField(decimal_places=0, default=100, max_digits=20, verbose_name='gold'),
        ),
    ]
