# Generated by Django 3.2.13 on 2022-07-04 15:51

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20220704_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='profile_image',
            field=models.ImageField(blank=True, default='images/logo_1080_1080.png', null=True, upload_to=account.models.profile_image_path),
        ),
    ]
