# Generated by Django 3.2.13 on 2022-07-11 11:49

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20220711_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='account',
            name='profile_image',
            field=models.ImageField(blank=True, default=account.models.default_profile_image, null=True, upload_to=account.models.profile_image_path),
        ),
    ]
