# Generated by Django 3.2.13 on 2022-07-18 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0007_alter_team_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='users',
        ),
    ]
