MESSAGE_TYPE_MESSAGE = 0 # NORMÁL ÜZENET
MESSAGE_TYPE_NUMBER_OF_ONLINE_USERS = 5 # A SZOBÁHOZ CSATLAKOZOTT FELHASZNÁLÓK SZÁMÁT JELZŐ ÜZENET

PUBLIC_CHAT_ROOM_MESSAGE_PAGE_SIZE = 10 # OLDALANKÉNT BETÖLTÖTT ÜZENETEK SZÁMA

STATIC_IMAGE_PATH_IF_DEFAULT_PIC_SET = '/static/images/blank_profile_image.png'