from datetime import datetime


MESSAGE_TYPE_MESSAGE = 0 # NORMÁL ÜZENET

MESSAGE_TYPE_JOIN = 3 # felhasználó belép a szobába
MESSAGE_TYPE_LEAVE = 4 # felhasználó kilép a szobából

MESSAGE_TYPE_NUMBER_OF_ONLINE_USERS = 5 # A SZOBÁHOZ CSATLAKOZOTT FELHASZNÁLÓK SZÁMÁT JELZŐ ÜZENET

PUBLIC_CHAT_ROOM_MESSAGE_PAGE_SIZE = 10 # OLDALANKÉNT BETÖLTÖTT ÜZENETEK SZÁMA
PRIVATE_CHAT_ROOM_MESSAGE_PAGE_SIZE = 10 # OLDALANKÉNT BETÖLTÖTT ÜZENETEK SZÁMA


STATIC_IMAGE_PATH_IF_DEFAULT_PIC_SET = '/static/images/blank_profile_image.png'


SUCCESS_MESSAGE_ON_FINDING_PRIVATE_CHAT = 'Got your private chat'


DEFAULT_SENDING_TIME = datetime.strptime('Jan 1 1970  1:00AM', '%b %d %Y %I:%M%p')